// descriptor_demo.js
// Scenario spec for the "Performance Analytics" (Descriptor) demo.
// A parent script is expected to render the Slack-like UI and play this script.

(function () {
  "use strict";

  // Static assets for this scenario
  const ASSETS = {
    // Charts generated by Descriptor in your run
    revenueTrend: "/mnt/data/5e46fa82-d7e3-48ad-925c-fb78e3541b4c.png",
    revenueByRegion: "/mnt/data/80768942-1f2c-47f1-9933-6f9a5b313e56.png",
    spendPerConversionTrend:
      "/mnt/data/e2e00192-98f2-4be0-a721-33a7efaa446a.png",
  };

  /**
   * Message script:
   *  - role: 'user' | 'app'
   *  - from: id for avatar / display name lookup
   *  - ts: timestamp label
   *  - type: optional hint ('controls', 'summary', 'attachment')
   *  - text: HTML-renderable string
   *  - file: optional file preview for the first user message
   *  - attachments: optional images for app messages
   *  - reactions: for the first user message, a list of reaction emoji names
   *  - controls: optional { primary, secondary } for inline buttons
   */
  const SCRIPT = [
    {
      role: "user",
      from: "amira",
      ts: "2:06 PM",
      text:
        '<span class="mention">@Carlos – Dark Wave</span> how is Search performing in terms of revenue, as of late?',
      file: {
        name: "digital_performance_sept_2025.csv",
        columns: [
          "date",
          "channel",
          "region",
          "device",
          "campaign",
          "brand",
          "audience",
          "spend",
          "clicks",
          "conversions",
          "impressions",
          "revenue",
        ],
        rows: [
          [
            "2025-03-21",
            "search",
            "US",
            "desktop",
            "Competitor",
            0,
            "prospect",
            771.75,
            66,
            1,
            1414,
            88.0,
          ],
          [
            "2025-03-21",
            "search",
            "US",
            "mobile",
            "Nonbrand Generic",
            0,
            "prospect",
            709.63,
            62,
            1,
            1127,
            85.09,
          ],
          [
            "2025-03-21",
            "search",
            "EU",
            "desktop",
            "Brand Core",
            1,
            "retarget",
            654.95,
            60,
            2,
            1088,
            193.39,
          ],
          [
            "2025-03-21",
            "search",
            "EU",
            "mobile",
            "Nonbrand Generic",
            0,
            "prospect",
            552.06,
            52,
            1,
            976,
            79.14,
          ],
          [
            "2025-03-21",
            "search",
            "APAC",
            "desktop",
            "Nonbrand Generic",
            0,
            "prospect",
            556.32,
            45,
            1,
            1038,
            86.76,
          ],
          [
            "2025-03-21",
            "search",
            "APAC",
            "mobile",
            "Nonbrand Generic",
            0,
            "prospect",
            562.79,
            51,
            1,
            971,
            85.88,
          ],
        ],
      },
      reactions: ["eyes", "hourglass_flowing_sand", "white_check_mark"],
    },

    {
      role: "app",
      from: "carlos",
      ts: "2:06 PM",
      type: "controls",
      text:
        "Descriptor controls — open the modal to set grouping, target metric, and filters",
      controls: {
        primary: "Controls",
        secondary: "Calculated Fields…",
      },
    },

    {
      role: "app",
      from: "carlos",
      ts: "2:06 PM",
      type: "summary",
      text:
        '<span class="pill pill-descriptor">📊 Performance Descriptor</span><br>' +
        "<strong>Grouping:</strong> channel, region<br>" +
        "<strong>Filters:</strong> channel in [search]<br>" +
        "<strong>Target Metric:</strong> revenue<br><br>" +
        "🧠 <strong>Summary:</strong> In the last 7 days ending September 16, 2025, revenue reached $9.2K, significantly higher than the 2-week moving average of $5.6K, marking a substantial increase of +63.8%. Compared to the 4-week moving average of $7.3K, this represents a +26.1% improvement, and it is also +11.5% above the 8-week moving average of $8.2K. Month-to-date, revenue stands at $20.4K, which is slightly below the 1-month aligned moving average of $20.5K by -0.6%, but up +2.0% compared to the 3-month aligned average of $20.0K. The projected revenue for the month is $38.2K, which is -4.8% lower than the 1-month moving average of $40.1K but +16.7% higher than the 6-month average of $32.7K. Currently, the efficiency metric for spend per conversion is $353, which is better than the mean of $370 and the median of $369. The top revenue regions are US at $10.7K, EU at $9.6K, and APAC at $7.2K.<br><br>" +
        "📅 <strong>Recent (last 7 days ending 2025-09-16):</strong><br>" +
        "– revenue: <strong>$9.2K</strong><br>" +
        "&nbsp;&nbsp;↳ vs 2W MA: <strong>$5.6K</strong> (↑ 63.8%)<br>" +
        "&nbsp;&nbsp;↳ vs 4W MA: <strong>$7.3K</strong> (↑ 26.1%)<br>" +
        "&nbsp;&nbsp;↳ vs 8W MA: <strong>$8.2K</strong> (↑ 11.5%)<br><br>" +
        "🗓️ <strong>Month-to-Date (through 2025-09-16):</strong><br>" +
        "– Projected month: <strong>$38.2K</strong><br>" +
        "&nbsp;&nbsp;↳ vs 1M MA: <strong>$40.1K</strong> (↓ -4.8%)<br>" +
        "&nbsp;&nbsp;↳ vs 3M MA: <strong>$39.4K</strong> (↓ -3.0%)<br>" +
        "&nbsp;&nbsp;↳ vs 6M MA: <strong>$32.7K</strong> (↑ +16.7%)<br><br>" +
        "💡 <strong>Top region this period:</strong><br>" +
        "&nbsp;&nbsp;↳ US: <strong>$10.7K</strong><br>" +
        "&nbsp;&nbsp;↳ EU: <strong>$9.6K</strong><br>" +
        "&nbsp;&nbsp;↳ APAC: <strong>$7.2K</strong>",
    },

    {
      role: "app",
      from: "carlos",
      ts: "2:06 PM",
      type: "attachment",
      text: "Generated plot from tool.",
      attachments: [
        {
          url: ASSETS.revenueTrend,
          caption:
            "Revenue trend (weekly) with 2, 4, and 8-week moving averages",
        },
      ],
    },

    {
      role: "app",
      from: "carlos",
      ts: "2:06 PM",
      type: "attachment",
      text: "Generated plot from tool.",
      attachments: [
        {
          url: ASSETS.revenueByRegion,
          caption: "Latest-period revenue by region",
        },
      ],
    },

    {
      role: "app",
      from: "carlos",
      ts: "2:06 PM",
      type: "attachment",
      text: "Generated plot from tool.",
      attachments: [
        {
          url: ASSETS.spendPerConversionTrend,
          caption: "Spend per conversion trend (weekly) with moving averages",
        },
      ],
    },
  ];

  // Register scenario on a global container the parent wrapper can read from.
  window.DWMS_DEMO_REGISTRY = window.DWMS_DEMO_REGISTRY || {};
  window.DWMS_DEMO_REGISTRY.descriptor = {
    id: "descriptor",
    tabLabel: "Performance Analytics",
    channel: "#carlos",
    participants: {
      amira: {
        displayName: "Amira K.",
        fullName: "Amira Khan",
        role: "user",
      },
      carlos: {
        displayName: "Carlos – Dark Wave",
        role: "app",
      },
    },
    script: SCRIPT,
  };
})();
